version: "3.5"

services:
  api:
    image: node:18.17.1
    volumes:
      - ./api:/app
    working_dir: /app
    command: >
      bash -c "npm install && npm run dev"
    ports:
      - 3333:3333
      - 9229:9229
    env_file:
      - ./api/.env
    depends_on:
      - db
    networks:
      - app-network

  front:
    image: node:18.17.1
    volumes:
      - ./front:/app
    working_dir: /app
    command: >
      bash -c "npm install && npm run serve"
    ports:
      - 3000:3000
    env_file:
      - ./front/.env
    depends_on:
      - api
    networks:
      - app-network

  db:
    container_name: postgres13_hackathon
    image: postgres:13
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_HOST}
    ports:
      - 54340:5432
    volumes:
      - hackathon_volume:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  hackathon_volume:
